import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

const f = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${f.className} bg`}>{children}</body>
    </html>
  )
}
